# Generated by Django 5.2.7 on 2025-10-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_projectimage_technologysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologysection',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
