# Generated by Django 5.2.7 on 2025-10-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_technologysection_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
