# Generated by Django 5.2.7 on 2025-10-12 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(upload_to='projects/%Y/%m/%d/'),
        ),
    ]
